# Generated by Django 4.1.4 on 2023-01-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_firstname_registration_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Lowest'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Highest')], default=2),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Process'), (2, 'Complated'), (3, 'Cancelled')], default=0),
        ),
    ]
