# Generated by Django 4.1.4 on 2023-01-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todo_priority_todo_updated_at_alter_todo_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
